config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  devise_for :users
  resources :audits  
  
  resources  :checklists do
    resource :audit
    
    get :switch_publishing_status, on: :member        
    
    get   :add_audit_fields,       on: :member
    patch :update_audit_fields,    on: :member    
  end  

  root  'checklists#index'
  get '*path', to: 'checklists#index'  
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, optional: true
  
  validates :answer,    presence: true   
  validates :comment,   presence: true, length: { minimum: 12 }  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audit.rb
# frozen_string_literal: true

class Audit < ApplicationRecord
  belongs_to :checklist
  belongs_to :user, optional: true
end

app/models/checklist.rb
# frozen_string_literal: true

class Checklist < ApplicationRecord

  has_many :questions, dependent: :destroy
  has_one  :audit
  has_one  :answer, through: :questions
  
  belongs_to :user, optional: true

  accepts_nested_attributes_for :questions, 
          allow_destroy: true
          # , reject_if: proc { |att| att['title'].blank? }                

  validates :title,         presence: true, length: { maximum: 40 }
  validates :description,   presence: true
  
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  
  # has_many    :answer,    dependent: :destroy
  belongs_to :checklist, optional: true  
  
  # accepts_nested_attributes_for :answer

  validates :title,         presence: true, length: { minimum: 12, maximum: 40 }
  validates :description,   presence: true    
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :checklists         
  has_many :audits  
  
  validates :email,              length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/audits_controller.rb
# frozen_string_literal: true

# Controller for user sees the list of audits
class AuditsController < ApplicationController

  before_action :set_audit, only: [:show, :destroy]

  def index
    @audits = Audit.page(params[:page]).per(10)
    @checklists = Checklist.where published: true
  end 
  
  def show
    @checklist = Checklist.find(@audit.checklist_id)
  end

  def destroy
    @audit.destroy
    redirect_to audits_path, notice: 'Audit was successfully destroyed.'
  end
  
  
  private
    def set_audit
      @audit = Audit.find(params[:id])
    end    
    
    # Only allow a list of trusted parameters through.
    def checklist_params
      params
        .require(:checklist)
        .permit(:title, :description,
          questions_attributes: Question.attribute_names.map(&:to_sym).push(:_destroy))
    end       
            
end  

app/controllers/channels/application_cable/channel.rb
module ApplicationCable
  class Channel < ActionCable::Channel::Base
  end
end

app/controllers/channels/application_cable/connection.rb
module ApplicationCable
  class Connection < ActionCable::Connection::Base
  end
end

app/controllers/checklists_controller.rb
# frozen_string_literal: true

# Controller for user sees the list of checklists
class ChecklistsController < ApplicationController
  before_action :set_checklist, only: [:show, :edit, :update, 
                                       :add_audit_fields, :update_audit_fields, 
                                       :switch_publishing_status, :destroy]

  def index
    @checklists = Checklist.page(params[:page]).per(10)        
  end
  
  def new
    @checklist = Checklist.new
    @checklist.questions.build
  end
  
  def create
    @checklist = Checklist.new(checklist_params)

    if @checklist.save
      redirect_to checklists_url, notice: 'Checklist was successfully created.' 
    else
      render :new 
    end    
  end  
  
  def show; end  
  
  def edit
  end
  
  def update
    if @checklist.update(checklist_params)
      redirect_to @checklist, notice: 'Checklist was successfully updated.'
    else
      render :edit 
    end
  end    
    
  def add_audit_fields
  end
  
  def update_audit_fields 
    @checklist = ChecklistService::SetAuditData.call(@checklist)    

    if @checklist.update(checklist_params) 
      redirect_to audits_path, notice: 'Audit was successfully created.' 
    else
      render :add_audit_fields
    end   
  end
  
  def switch_publishing_status
    @checklist.published = !@checklist.published
    @status_ar = ['Unpublish', 'Publish']
    @checklist.next_publish_status = @status_ar.delete(@checklist.next_publish_status)
    @checklist.next_publish_status = @status_ar[0]
    @checklist.save
    
    redirect_to checklist_path(@checklist), notice: 'Checklist Status was successfully updated.'
  end
  
  def destroy
    @checklist.destroy
    redirect_to checklists_url, notice: 'Checklist was successfully destroyed.'
  end
    
  
  private
    def set_checklist
      @checklist = Checklist.find(params[:id])
    end  

    # Only allow a list of trusted parameters through.
    def checklist_params
      params
      #  .require(:checklist)
      #  .permit(:title, :description,
      #    questions_attributes: [:id, :checklist_id, :title, :description, :created_at, 
      #                           :updated_at, :answer, :comment, :skip_validation, :_destroy, 
      #                  answer: [:answer, :comment, :id, :question_id, :_destroy]])
       params
         .require(:checklist)
         .permit(:title, :description,
           questions_attributes: Question.attribute_names.map(&:to_sym).push(:_destroy))          
    end        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/audits/_fill_checklist.html.haml
/ Button trigger modal
%button.btn{"data-target" => "#exampleModalLong", "data-toggle" => "modal", :type => "button"}
  Fill checklist
  
/ Modal
#exampleModalLong.modal.fade.audits-modal-form{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLongTitle", role: "dialog", :tabindex => "-1"}
  .modal-dialog{role: "document"}
    .modal-content
    
      .modal-header
        %h5
          Checklists:
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
          
      .modal-body
        = render 'modal_content_checklists'
        

app/views/audits/_modal_content_checklists.html.haml
- @checklists.each do |checklist|
  = link_to add_audit_fields_checklist_path(checklist) do
    = checklist.title
    %br/

app/views/audits/_question_fields.html.haml
.nested-fields
  %b
    Question:
  = f.object.title
  %br/

  %b
    Description:
  = f.object.description
  %br/

  = f.input :answer, as: :select, collection: [ 'yes', 'no', 'NA' ], prompt: 'Select Answer', label: false, required: 'required'

  %b
    Comment:
  = f.input :comment, label: false, placeholder: 'Your comment', required: 'required', pattern: ".{12,}", title: "12 characters minimum"

  = f.hidden_field :id
  = f.hidden_field :_destroy  

    
  %br/
    
    
-#%tr.nested-fields
  %td
    = link_to_remove_association "remove", f, class: 'btn btn-primary btn-xs' 

  %td
    = f.input :answer, label: false, required: 'required'
  %td
    = f.input :comment, label: false, required: 'required', pattern: ".{12,}", title: "12 characters minimum"
  
  = f.hidden_field :id
  = f.hidden_field :_destroy    

app/views/audits/index.html.haml
%h2 Audits

%table
  %thead
    %tr
      %th 
        Checklist name
      %th 
        Last updated timestamp
      %th{:colspan => "3"}
        Actions 
  %tbody
    - @audits.each do |audit|	
      %tr
        %td
          = link_to audit do
            = @checklists.find(audit.checklist_id).title
        %td
          = link_to audit do
            = audit.updated_at
        %td
          = link_to 'Edit', add_audit_fields_checklist_path(@checklists.find(audit.checklist_id)), class: 'btn teal lighten-2'
          = link_to 'Destroy', audit, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn red lighten-2'

= paginate @audits

= render 'fill_checklist'

app/views/audits/show.html.haml
%p
  %strong Checklist Title:
  = @checklist.title
%p
  %strong Checklist Description:
  = @checklist.description


%table.table
  %thead
    %tr
      %th Question Title
      %th Description
      %th Answer
      %th Comment

  %tbody.fields
    - @checklist.questions.each do |question|   
      %tr
        %td 
          = question.title

        %td 
          = question.description
          
        %td 
          = question.answer

        %td 
          = question.comment          


= link_to 'Edit', add_audit_fields_checklist_path(@checklist)
|
\#{link_to 'To Audits Page', audits_path}

app/views/checklists/_answer_fields.html.haml
.k
  = f.input :answer, as: :select, collection: [ 'yes', 'no', 'NA' ], prompt: 'Select Answer', required: 'required'

  = f.input :comment, placeholder: 'Your comment', required: 'required'

  = f.hidden_field :id
  = f.hidden_field :_destroy  

    
  %br/
    
    

app/views/checklists/_audit_fields_form.html.haml
= simple_form_for @checklist, url: update_audit_fields_checklist_path(@checklist) do |f|

  - if f.error_notification
    %p
      .alert.alert-danger  
        = f.error_notification
    
  %h4
    Checklist 
    = @checklist.title 
  %br/  

  = f.simple_fields_for :questions do |builder|
    = render 'audit_question_fields', f: builder
        
  .questions
    .form-actions
      = f.button :submit, 'Save', class: 'btn'
      = link_to 'Cancel Saving', audits_path, class: 'btn'
    
    
-#= simple_form_for @checklist, url: checklist_audit_path, method: :post do |f|
  = f.error_notification
  .form-inputs
    = f.input :title
    = f.input :description  

  %table
    %thead
      %tr
        %th Question Actions
        %th Question Title
        %th Question Description
        
    %tbody.questions
      = f.simple_fields_for :questions do |builder|
        = render 'question_fields', f: builder

  .form-actions
    = f.button :submit, 'Save'
    

app/views/checklists/_audit_question_fields.html.haml
.nested-fields
  %b
    Question:
  = f.object.title  
  %br/

  %b
    Description:
  = f.object.description
  %br/
  %br/

  %b
    Enter the answer:
  = f.input :answer, as: :select, collection: [ 'yes', 'no', 'NA' ], prompt: 'Select Answer', label: false, required: 'required'

  %b
    Comment:
  = f.input :comment, label: false, placeholder: 'Your comment', pattern: ".{12,}", title: "12 characters minimum", required: 'required'

  = f.hidden_field :title
  = f.hidden_field :id
  = f.hidden_field :_destroy  
  
  -#= f.simple_fields_for :answers do |builder|
    = render 'answer_fields', f: builder  

    
  %br/
    
    
-#%tr.nested-fields
  %td
    = link_to_remove_association "remove", f, class: 'btn btn-primary btn-xs' 

  %td
    = f.input :answer, label: false, required: 'required'
  %td
    = f.input :comment, label: false, required: 'required', pattern: ".{12,}", title: "12 characters minimum"
  
  = f.hidden_field :id
  = f.hidden_field :_destroy    

app/views/checklists/_form.html.haml
= simple_form_for(@checklist) do |f|

  - if f.error_notification
    %p
      .alert.alert-danger  
        = f.error_notification
    
  .form-inputs
    %b
      Enter the title:          
    = f.input :title, label: false, placeholder: 'Title'
    %br/
    
    %b
      Description: 
    %br/     
    %br/
    = f.input :description, label: false, placeholder: 'Description'	

  %table
    %thead
      %tr
        %th Question Actions
        %th Question Title
        %th Question Description
        
    %tbody.questions
      = f.simple_fields_for :questions do |builder|
        = render 'question_fields', f: builder

  .form-actions    
    = link_to_add_association 'Add Question', f, 
      :questions, class: 'btn btn-primary', 
      data: { association_insertion_node: '.questions', association_insertion_method: :append }
    = f.button :submit, class: 'btn'
    = link_to 'Cancel Saving', checklists_path, class: 'btn'    
    

app/views/checklists/_question_fields.html.haml
%tr.nested-fields
  %td
    = link_to_remove_association "remove", f, class: 'btn btn-primary btn-xs btn-additional' 

  %td
    = f.input :title, label: false
  %td
    = f.input :description, label: false
  
  = f.hidden_field :id
  = f.hidden_field :_destroy  

app/views/checklists/add_audit_fields.html.haml
= render 'audit_fields_form', checklist: @checklist

app/views/checklists/edit.html.haml
%h4 Editing Checklist

= render 'form', checklist: @checklist

app/views/checklists/index.html.haml
%h2 Checklists

%table
  %thead
    %tr
      %th Title
      %th Description
      %th Actions
  %tbody
    - @checklists.each do |checklist|	
      %tr
        %td
          = link_to checklist do
            = checklist.title
        %td
          = link_to checklist do
            = checklist.description
        %td
          = link_to checklist.next_publish_status, switch_publishing_status_checklist_path(checklist), class: 'btn teal lighten-2'
          = link_to 'Edit', edit_checklist_path(checklist), class: 'btn teal lighten-2'
          = link_to 'Destroy', checklist, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn red lighten-2'
          
= paginate @checklists
          
%br/
= link_to 'New Checklist', new_checklist_path, class: 'btn', class: 'btn'        

app/views/checklists/new.html.haml
%h4 New Checklist

= render 'form', checklist: @checklist

app/views/checklists/show.html.haml
%p
  %strong Checklist Title:
  = @checklist.title
%p
  %strong Checklist Description:
  = @checklist.description
  
%p
  %strong Published:
  = @checklist.published  


%table.table
  %thead
    %tr
      %th Question Title
      %th Description

  %tbody.fields
    - @checklist.questions.each do |question|   
      %tr
        %td 
          = question.title

        %td 
          = question.description


= link_to 'Edit', edit_checklist_path(@checklist), class: 'btn'
= link_to 'To Checklists Page', checklists_path, class: 'btn'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Ssandbox
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      .row
        .col.s6
          - if notice
            %p.alert.alert-success
              = notice
            - if ['Welcome! You have signed up successfully.', 'Signed in successfully.'].include?(notice)
              #authorization_pop_up
                = notice  
                
          - if alert
            %p.alert.alert-danger
              = alert 
            - if alert == 'Invalid Email or password.'
              #authorization_pop_up
                = alert  
    
              
          %p.navbar-text.float-right
          
            - if user_signed_in?
              Logged in as
              = succeed "." do
                %strong= current_user.email
                
              = link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link btn teal lighten-2'              
              = link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link btn teal lighten-2'
              
            - else
              = link_to "Sign up", new_user_registration_path, class: 'navbar-link btn teal lighten-2'
              
              = link_to "Login", new_user_session_path, class: 'navbar-link btn teal lighten-2'
                     
          = yield